package br.com.analisadorc;

public enum TokenType {
    // Palavras-chave
    AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO, DOUBLE,
    ELSE, ENUM, EXTERN, FLOAT, FOR, GOTO, IF, INLINE, INTEGER, LONG,
    REGISTER, RESTRICT, RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT,
    SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, WHILE,
    _BOOL, _COMPLEX, _IMAGINARY, _ATOMIC, _THREAD_LOCAL, LIBRARY, HEADER_FILE, PREPROCESSOR_KEYWORD, BITWISE, BITWISENOT, CONSTANT_HEX, CONSTANT_BIN,
    CONSTANT_FLOAT,

    // Operadores
    PLUS, MINUS, MULTIPLY, DIVIDE,
    ASSIGN, EQUAL, NOT_EQUAL,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL, LBRACKET, RBRACKET, OPERATOR, COMPARISON, LOGICAL, AMPERSAND,

    // Delimitadores
    LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COMMA,

    // Literais e identificadores
    IDENTIFIER, NUMBER, STRING, CHAR_LITERAL,

    // Comentário
    COMMENT,

    // Outros
    EOF, INCLUDE, IFNDEF, IFDEF, ENDIF, DEFINE, KEYWORD, SYMBOL, UNKNOWN, INT, ERROR
}
